# Generated by Django 4.2.6 on 2023-10-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_rename_product_cartitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
